remote_theme: jemalare/texture

url: https://gagnefsbyn.se
title: Gagnefsbyn.se
author: Jens Målare
email: info@gagnefsbyn.se
lang: sv
description: > # this means to ignore newlines until "show_exerpts:"
  Välkommen till byföreningens hemsida! Läs om byarna, bystugan, föreningen 
  och få information om de aktiviteter vi ordnar. Här finns också notiser och
  dokument från vår syskonförening _Nordåker-Gagnefsbyns vägsamfällighet_.
  Bystugan är vår samlingslokal och du får gärna [hyra den](bystugan) för fest eller möten!
  Ni kan prenumerera på våra e-postutskick som rör aktiviteter i
  föreningen, kontakta info@gagnefsbyn.se så lägger vi till er på listan.
show_excerpts: false # set to true to show excerpts on the homepage
# baseurl: /
permalink: /posts/:year-:month-:title/

texture:
  title: Byföreningen
  tagline: Nordåker, Gagnefsbyn, Nordbäck och Älvnäs
  date_format: "%b %-d, %Y"  # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  # social_links:
  #   twitter: thelehhman
  #   github:  thelehhman
  #   linkedIn: in/thelehhman
  #   rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  -
    scope:
      path:            "assets/**"
    values:
      sitemap:         false
